### ISSUE TITLE
Port to TelepathyGLib

### ISSUE THREAD

**Issue by pro-panda** [sugarlabs/sugar-toolkit-gtk3#402]
Telepathy python bindings need to be ported to PyGObject bindings

Partial work was done in #389 and #401 

Useful resources:
 - [TelepathyGLib Documentation](https://lazka.github.io/pgi-docs/#TelepathyGLib-0.12)
 - [Telepathy Documentation](https://telepathy.freedesktop.org/components/documentation/)

**Comment by nityanandagohain** [comment]
@pro-panda Hii, can I start working on this.

**Comment by quozl** [comment]
@nityanandagohain, please don't ask to start working.  Just start working.  See [contributing](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md) "_there is no need to ask permission to work on an issue._"

**Comment by HAKSOAT** [comment]
@pro-panda Hello, I'm interested in working on this project. I'd appreciate if you help me with some more information asides the indicated useful resources.

**Comment by quozl** [comment]
@HAKSOAT, thanks for your interest, but please use the [mailing list sugar-devel@lists.sugarlabs.org](http://lists.sugarlabs.org/listinfo/sugar-devel) for general questions, so that we can keep issue discussions on topic.  I'm happy to give a more detailed answer there.  I'll delete my comment here and yours after a few minutes.

**Comment by quozl** [comment]
https://github.com/sugarlabs/sugar-toolkit-gtk3/commit/88ea8e1f4febee5f8371337f07116e22c9d54cb6
